package de.empulse.springbootin10steps.StudentService;

import de.empulse.springbootin10steps.entity.Student;
import de.empulse.springbootin10steps.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * TODO: Add class description
 *
 * @author Tycho Schottelius, empulse GmbH, 2020-04-01
 */
@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;

    // each instance of student will have its own id generated by MongoDB
    public Student createStudent(Student student) {
        return studentRepository.save(student);
    }
}
